services:
  postgres:
    image: postgres:15
    container_name: fraud_detection_db
    environment:
      POSTGRES_DB: fraud_detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # Remove the problematic POSTGRES_INITDB_ARGS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    # Add health check to ensure database is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fraud_detection"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: